### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by kolayne** [SlidEnergy/life-calendar#1]
Hi! Thank you for your work! 
In case you want people to be able to contribute to your project or use posts of it in their own code, you should choose a license for your repository. More details: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by SlidEnergy** [comment]
Hi,  Nikolay.
Ok. I added the MIT License. How do you plan to use it?

**Comment by kolayne** [comment]
Thank you! I'm not yet sure about my plans, but I'm working on an education project which is going to extend the life calendar application and our team will probably want to use some pieces of code from already existing similar projects
